# See https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    # Disabled because of IRC command constants
    constant_identifier_names: false
    # Disabled because we have so many of these
    # TODO: get rid of them
    prefer_const_constructors: false
    prefer_is_empty: false
    avoid_print: false
